spring.application.name=Payment-gateway
razorpay.key_id=rzp_test_5bBJp0v0qQSdv2
razorpay.key_secret=Yudsw2n9WuRjBdA0Qnz5FvLX

spring.datasource.url=jdbc:mysql://localhost:3306/payment_db
spring.datasource.username=root
spring.datasource.password=nikhil123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikhilprasad428@gmail.com
spring.mail.password=zntf qcjd hyxg cdbt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
